# Configuration for Label Commenter - https://github.com/peaceiris/actions-label-commenter

labels:
  - name: Invalid
    labeled:
      issue:
        body: This issue has been closed because it does not seem right.
        action: close
  - name: Need More Info
    labeled:
      issue:
        body: We would appreciate it if you could provide us with more info about this issue!
  - name: ðŸŽ¯ Roadmap
    labeled:
      issue:
        body: |
          This issue has been added to the latest roadmap. :tada:
  - name: Support
    labeled:
      issue:
        body: |
          :wave: Hey there! we use the issue tracker exclusively for bug reports and feature requests. However, this issue appears to be a support request.
          Please use our [support channels](https://github.com/next-theme/hexo-theme-next#feedback) to get help with the project.
        action: close
  - name: Wontfix
    labeled:
      issue:
        body: There wasn't enough interest from the team or community to implement this change. Thanks for contributing and we appreciate your understanding.
        action: close
  - name: Configurations
    labeled:
      pr:
        body: |
          This pull request contains changes to the configuration file. Please make sure the documentation in [NexT website](https://theme-next.js.org/docs/) is changed or added.
          Please edit relevant source files here: https://github.com/next-theme/theme-next-docs/tree/master/source/docs and create a pull request with the changes here: https://github.com/next-theme/theme-next-docs/pulls
