name: Tester

on: [push, pull_request]

jobs:
  tester:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          repository: hexojs/hexo-starter
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-cache
          restore-keys: ${{ runner.os }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - uses: actions/checkout@v2
        with:
          path: themes/next
      - uses: actions/checkout@v2
        with:
          repository: SukkaLab/hexo-many-posts
          path: source/_posts/hexo-many-posts
      - run: npx hexo config theme next
      - name: Test
        run: npx hexo g
