name: Tester

on: [push, pull_request]

jobs:
  tester:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          repository: hexojs/hexo-starter
      - name: Use Node.js
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm install
      - name: Install hexo-tag-embed
        run: npm install hexo-tag-embed
      - uses: actions/checkout@v4
        with:
          path: themes/next
      - uses: actions/checkout@v4
        with:
          repository: hexojs/hexo-many-posts
          path: source/_posts/hexo-many-posts
      - run: npx hexo config theme next
      - uses: DamianReeves/write-file-action@master
        with:
          path: themes/next/scripts/error.js
          contents: |
            hexo.log.error = function(...params) {
              console.error("ERROR", ...params);
              process.exit(1);
            }
      - name: Test
        run: npx hexo g
